# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "34844b5c7e11179844d2863504645419"
name = "backtrack-app"
handle = "backtrack-app"
application_url = "https://exemption-heights-pink-duties.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "backtracktest1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://exemption-heights-pink-duties.trycloudflare.com/auth/callback",
  "https://exemption-heights-pink-duties.trycloudflare.com/auth/shopify/callback",
  "https://exemption-heights-pink-duties.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
